version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: unless-stopped

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  main:
    image: docker.io/slexxa/otus_hl_main:v0.0.1
    container_name: main
    restart: unless-stopped

    ports:
      - "8000:8000"
volumes:
  postgres_data:
