basePath: /
definitions:
  main.Body:
    properties:
      text:
        type: string
    type: object
  main.Message:
    properties:
      created_at:
        type: string
      from_user:
        type: string
      id:
        type: integer
      text:
        type: string
      to_user:
        type: string
    type: object
info:
  contact: {}
  description: Otus HighLoad
  title: Auth Service API
  version: "1.0"
paths:
  /dialog/{user_id}/list:
    get:
      parameters:
      - description: User
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Message'
            type: array
      security:
      - BearerAuth: []
      summary: Get dialog
      tags:
      - dialog
  /dialog/{user_id}/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: Receiver
        in: path
        name: user_id
        required: true
        type: string
      - description: text
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/main.Body'
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Send message
      tags:
      - dialog
securityDefinitions:
  BasicAuth:
    type: basic
  BearerAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
