{
 "title": "otusapp",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency by Flask",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "method=GET, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"GET\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"GET\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"GET\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "method=DELETE, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"DELETE\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"DELETE\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"DELETE\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "method=POST, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"POST\", path=~\"/api/v1/user\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"POST\", path=~\"/api/v1/user\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"POST\", path=~\"/api/v1/user\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "method=PUT, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"PUT\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"PUT\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(flask_http_request_duration_seconds_bucket{method=\"PUT\", path=~\"/api/v1/user/.*\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency by ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "method=GET, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"GET\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "method=DELETE, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"DELETE\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "method=POST, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"POST\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "method=PUT, path=/api/v1/user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[5m])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[5m])))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=\"PUT\"}[5m])))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  },
  {
   "title": "RPS by Flask",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(flask_http_request_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RPS by ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors by Flask",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "error rate with 5XX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(flask_http_request_exceptions_total{status=~\"5.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors by ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "error rate with 5XX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}